; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
build_src_filter = +<*> -<ir_calibrate.cpp>
lib_deps =
    arduino-libraries/Servo
    adafruit/Adafruit BNO08x

[env:megaatmega2560_test]
platform = atmelavr
board = megaatmega2560
framework = arduino
build_src_filter = +<*> -<main.cpp> -<strafetest.cpp> -<ir_calibrate.cpp> +<../test/test_movement/test_main.cpp>
lib_deps =
    arduino-libraries/Servo
    adafruit/Adafruit BNO08x

[env:test_sensors]
platform = atmelavr
board = megaatmega2560
framework = arduino
build_src_filter = -<*> +<../test/test_sensors/test_sensors.cpp>
monitor_speed = 115200

[env:ir_calibrate]
platform = atmelavr
board = megaatmega2560
framework = arduino
build_src_filter = -<*> +<ir_calibrate.cpp>
monitor_speed = 115200

[env:test_rotation]
platform = atmelavr
board = megaatmega2560
framework = arduino
build_src_filter = -<*> +<percepetion.cpp> +<movement.cpp> +<../test/test_rotation.cpp>
lib_deps =
    arduino-libraries/Servo
    adafruit/Adafruit BNO08x
monitor_speed = 115200

[env:test_run]
platform = atmelavr
board = megaatmega2560
framework = arduino
build_src_filter = -<*> +<percepetion.cpp> +<movement.cpp> +<../test/test_run.cpp>
lib_deps =
    arduino-libraries/Servo
    adafruit/Adafruit BNO08x
monitor_speed = 115200

[env:test_homing]
platform = atmelavr
board = megaatmega2560
framework = arduino
build_src_filter = -<*> +<percepetion.cpp> +<movement.cpp> +<../test/test_homing.cpp>
[env:test_wired]
platform = atmelavr
board = megaatmega2560
framework = arduino
build_src_filter = -<*> +<percepetion.cpp> +<movement.cpp> +<../test/test_sensors/testmainwired.cpp>
lib_deps =
    arduino-libraries/Servo
    adafruit/Adafruit BNO08x
monitor_speed = 115200
